
info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

foo: b
test: This is a test
bar: Spring Boot Tiago Vaz Teixeira GIT diferente

server:
  port: 8080
---

spring:
    profiles: development
server:
    port: 9001

---

spring:
    profiles: prod
server:
    port: 8085
